#!/bin/bash

set -o errexit
set -o pipefail

TRAP_SHUTDOWN=0
MAX_CHILDEN=25

trap 'TRAP_SHUTDOWN=1' SIGINT SIGTERM

WEBAPP_PROFILE=${WEBAPP_PROFILE-/vault/secrets/config}
WEBAPP_VERSION=${WEBAPP_VERSION-0000000}
WEBAPP_ADDRESS=${WEBAPP_ADDRESS-0.0.0.0}
WEBAPP_PORT=${WEBAPP_PORT-8080}
WEBAPP_LOG_LEVEL=${WEBAPP_LOG_LEVEL-info}
WEBAPP_APPLICATION=${WEBAPP_APPLICATION-app.webapp:GAPPLICATION}
WEBAPP_DATABASE=${WEBAPP_DATABASE-none}
WEBAPP_CHILDREN=${WEBAPP_CHILDREN-001}
export WEBAPP_PROFILE WEBAPP_VERSION WEBAPP_ADDRESS WEBAPP_PORT WEBAPP_LOG_LEVEL WEBAPP_APPLICATION WEBAPP_DATABASE WEBAPP_CHILDREN

[ -f $WEBAPP_PROFILE ] && source $WEBAPP_PROFILE

[ ! -z "${WEBAPP_CHILDREN##*[!0-9]*}" ] || exit 1

for ((INDEX=1; INDEX<=WEBAPP_CHILDREN; INDEX++));
do
    gunicorn3 --bind $WEBAPP_ADDRESS:$WEBAPP_PORT --log-level $WEBAPP_LOG_LEVEL --access-logfile - --error-logfile - $WEBAPP_APPLICATION &
    export WEBAPP_PORT=$((WEBAPP_PORT+1))
    [ $INDEX -eq $MAX_CHILDEN ] && break
done

while [ $TRAP_SHUTDOWN -eq 0 ]; do sleep 1; done

kill -TERM $(jobs -p)

exit 0