name: webapp
on: [push]
jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        registry: ${{ secrets.DOCKERHUB_REGISTRY }}
    - run: ./build.sh
    - uses: docker/build-push-action@v2
      with:
        push: true
        context: "{{defaultContext}}:mysubdir"
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.workflow }}:${{ github.sha }}