name: webapp
on: [push]
jobs:
  image-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_REGISTRY }}
        DOCKER_REPOSITORY: webapp
      run: ./build.sh
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        registry: ${{ secrets.DOCKERHUB_REGISTRY }}
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp:1002
